# FTML Project

In [9]:
from sklearn.ensemble import (
    RandomForestRegressor,
    AdaBoostRegressor,
    BaggingRegressor,
    GradientBoostingRegressor,
    HistGradientBoostingRegressor,
)

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
import numpy as np

X_train = np.load("../data/regression/X_train.npy")
X_test = np.load("../data/regression/X_test.npy")
Y_train = np.squeeze(np.load("../data/regression/y_train.npy"))
Y_test = np.squeeze(np.load("../data/regression/y_test.npy"))

print(X_test)

[[0.21299085 0.15793756 0.15385995 ... 0.03363709 0.13454801 0.78253074]
 [0.76968704 0.38497069 0.07402732 ... 0.65857444 0.33445438 0.00229702]
 [0.1881224  0.97026479 0.98560911 ... 0.12440952 0.95665322 0.0659203 ]
 ...
 [0.93365216 0.53675255 0.80927242 ... 0.10679115 0.76153087 0.22111448]
 [0.42781714 0.74237926 0.6231648  ... 0.35784022 0.53559913 0.96028974]
 [0.14952304 0.49762269 0.08090538 ... 0.6501903  0.37003847 0.01634557]]


In [ ]:
polynomial_2 = make_pipeline(PolynomialFeatures(3, include_bias=False))

model = make_pipeline(
        polynomial_2,
        GradientBoostingRegressor(random_state=572),
    )

model.fit(X_train, Y_train)
score = model.score
print(score)

y_pred = model.predict(X_test)
r2_score = r2_score(y_test, y_pred)
print(r2_score)

/home/alex/afs/Master/FTML_project/venv/lib/python3.13/site-packages/sklearn/ensemble/_gb.py:672: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?
